frontend:
  build:
    context: ./react_frontend
    dockerfile: Dockerfile.prod
    args:
      REACT_APP_API_BASE: "/api"
  container_name: react_frontend
  restart: unless-stopped
  volumes:
    - ./react_frontend/nginx.conf:/etc/nginx/nginx.conf:ro
  ports:
    - "80:80"
  depends_on:
    - api
  networks:
    - app_network
